List<String> getLyrics() {
  return [
    'Un, dos, tres',
    'Si yo te entrego',
    'Todo el amor que te tengo',
    'Promete que no fallaras',
    'Y que siempre estarás',
    'Justo acá',
    'Si yo te juro',
    'Un amor verdadero',
    'Promete que también lo harás',
    'Y que juntos vamos a estar hasta el final',
    'Cada día que en mi mente estás',
    'Eres como una estrella fugaz',
    'Estás volando de aquí para allá',
    'Brillas y brillas que hermosa estás',
    'Eres la luna, el sol, mis estrellas',
    'Quisiera tenerte un poco más cerca',
    'Y es que eres tan real',
    'Contigo el tiempo no me importa ya',
    'El reloj puede pasar y pasar',
    'Y es tan hermoso porque en realidad',
    'Yo sí me quedó con ganas de más',
    'Eres la luna, el sol, mis estrellas',
    'Quisiera tenerte un poco más cerca',
    'Y es que eres tan real',
    'Eso es lo que a ti te hace especial',
    'Y si te robo al menos solo un beso',
    'Prométeme que igual lo harás',
    'Hasta que nos lleguemos a desgastar',
    'Y si te digo que enserio yo te amo',
    'No tengas prisa de decirlo, decirlo',
    'Yo quiero que lo digas cuando lo sientas',
    'Con el corazón, porque no te obligaré amor',
    'Cada día que en mi mente estás',
    'Eres como una estrella fugaz',
    'Estás volando de aquí para allá',
    'Brillas y brillas que hermosa estás',
    'Eres la luna, el sol, mis estrellas',
    'Quisiera tenerte un poco más cerca',
    'Y es que eres tan real',
    'Contigo el tiempo no me importa ya',
    'El reloj puede pasar y pasar',
    'Y es tan hermoso porque en realidad',
    'Yo sí me quedó con ganas de más',
    'Eres la luna, el sol, mis estrellas',
    'Quisiera tenerte un poco más cerca',
    'Y es que eres tan real',
    'Eso es lo que a ti te hace especial',
    'Cariño, te pido',
    'Que por favor, prometas',
    'Que no me fallarás',
    'Contigo quiero estar',
    'Hasta el final',
    'No digas que te iras',
    'No te vayas a marchar',
    'Porque yo no podré, si no estás',
    'Noo, noo'
  ];
}
